#!/bin/bash

# Fix deployment by moving config directory out of functions folder
# This prevents Supabase from trying to bundle it during deployment

echo "🔧 Fixing TheLoopGPT Backend Deployment..."

# Step 1: Move config directory to project root
echo "📦 Moving config directory..."
if [ -d "supabase/functions/_lib/config" ]; then
  mv supabase/functions/_lib/config ./metadata-config
  echo "✅ Moved supabase/functions/_lib/config → ./metadata-config"
else
  echo "⚠️  Config directory not found (may already be moved)"
fi

# Step 2: Update bundle script to use new location
echo "📝 Updating bundle script..."
cat > bundle-metadata.js << 'EOF'
#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const configDir = path.join(__dirname, 'metadata-config');
const outputFile = path.join(__dirname, 'supabase/functions/mcp-server/metadata_bundled.ts');

console.log('📦 Bundling metadata from:', configDir);

const types = fs.readFileSync(path.join(configDir, 'types.ts'), 'utf8');
const theloopgptMetadata = fs.readFileSync(path.join(configDir, 'theloopgptMetadata.ts'), 'utf8');
const toolDescriptions = fs.readFileSync(path.join(configDir, 'toolDescriptions.ts'), 'utf8');
const routingHints = fs.readFileSync(path.join(configDir, 'routingHints.ts'), 'utf8');
const index = fs.readFileSync(path.join(configDir, 'index.ts'), 'utf8');

function removeImports(content) {
  return content
    .replace(/export\s+type\s*\{[^}]*\}\s*from\s+['"].*['"];?/gs, '')
    .replace(/export\s*\{[^}]*\}\s*from\s+['"].*['"];?/gs, '')
    .replace(/^import\s+type\s+\{[^}]+\}\s+from\s+['"].*['"];?\s*$/gm, '')
    .replace(/^import\s+type\s+.*from\s+['"].*['"];?\s*$/gm, '')
    .replace(/^import\s+.*from\s+['"].*['"];?\s*$/gm, '');
}

const bundled = \`/**
 * BUNDLED METADATA - AUTO-GENERATED
 * DO NOT EDIT THIS FILE DIRECTLY
 * Generated from metadata-config/* files
 * Run: node bundle-metadata.js to regenerate
 */

// ============================================================================
// TYPES
// ============================================================================
\${removeImports(types)}

// ============================================================================
// THELOOPGPT METADATA
// ============================================================================
\${removeImports(theloopgptMetadata)}

// ============================================================================
// TOOL DESCRIPTIONS
// ============================================================================
\${removeImports(toolDescriptions)}

// ============================================================================
// ROUTING HINTS
// ============================================================================
\${removeImports(routingHints)}

// ============================================================================
// CONVENIENCE FUNCTIONS (from index.ts)
// ============================================================================
\${removeImports(index)}
\`;

fs.writeFileSync(outputFile, bundled);
console.log(\`✅ Bundled metadata written to: \${outputFile}\`);
console.log(\`📊 File size: \${(fs.statSync(outputFile).size / 1024).toFixed(2)} KB\`);
EOF

chmod +x bundle-metadata.js

# Step 3: Regenerate bundled file
echo "🔄 Regenerating bundled metadata..."
node bundle-metadata.js

# Step 4: Verify no problematic imports
echo "🔍 Verifying bundled file..."
EXPORT_COUNT=$(grep -c "} from" supabase/functions/mcp-server/metadata_bundled.ts || echo "0")
if [ "$EXPORT_COUNT" -eq "1" ]; then
  echo "✅ Bundled file looks good (only comment contains 'from')"
else
  echo "⚠️  Found $EXPORT_COUNT instances of '} from' - may need manual review"
fi

# Step 5: Git operations
echo "📝 Committing changes..."
git add -A
git commit -m "fix: Move config directory out of functions folder to prevent bundling conflicts"

echo ""
echo "✅ Fix complete! Next steps:"
echo "1. Push to GitHub: git push origin master"
echo "2. Deploy: supabase functions deploy mcp-server --no-verify-jwt"
echo "3. Test all 5 endpoints"
